# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dot Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dot Test
  pod 'Alamofire', '5.1'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'ImageViewer.swift', '~> 3.0'
  pod 'ImageViewer.swift/Fetcher', '~> 3.0'

  target 'Dot TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dot TestUITests' do
    # Pods for testing
  end

end
